
services:
  backend:
    image: backend:latest
    build: backend
    ports:
      - "5000:5000"

  frontend:
    image: frontend:latest
    build: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend